Repository SoftboxLab/moo-cli, pull requests merged in 2018-09, with the labels that each got.

#33 Feature/typescript
  assets/vue-presets.json
  package.json
  src/commands/arch.ts
  src/commands/comp.ts
  src/commands/vue.ts
  src/index.ts
  src/templates/react.ts
  src/templates/react/comp.ts
  src/templates/react/compTS.ts
  src/templates/vue.ts
  src/templates/vue/compTS.ts
  src/templates/vue/presets.ts
  src/utils/options.ts
Labels: enhancement

#35 Release/v0.4.0
  assets/vue-presets.json
  package-lock.json
  package.json
  src/commands/arch.ts
  src/commands/comp.ts
  src/commands/vue.ts
  src/index.ts
  src/templates/react.ts
  src/templates/react/comp.ts
  src/templates/react/compTS.ts
  src/templates/vue.ts
  src/templates/vue/compTS.ts
  src/templates/vue/presets.ts
  src/utils/options.ts
Labels: enhancement

#37 Gandalf-lint
  src/commands/vue.ts
  src/templates/vue/js-def-cfgs.ts
  src/templates/vue/js-def-deps.ts
  src/utils/console.ts
Labels: enhancement, help wanted

#38 Release/v0.5.0
  package-lock.json
  package.json
  src/commands/vue.ts
  src/templates/vue/js-def-cfgs.ts
  src/templates/vue/js-def-deps.ts
  src/utils/console.ts
Labels: enhancement

#39 Release/v0.5.1
  README.md
  package-lock.json
  package.json
Labels: bug
